require 'pry'
require_relative '../app/models/artist.rb'
require_relative '../app/models/gallery.rb'
require_relative '../app/models/painting.rb'
require '/Users/keshalake/development/code/OO-Art-Gallery-atlanta-web-042219/app/models/purchase.rb'
